### ISSUE TITLE
Annotatie rechtspraak als rechtsliteratuur

### ISSUE THREAD

**Issue by mvwestendorp** [mvwestendorp/v-en-a#28]
> Rechtsleer: verwijzing naar een noot met titel lijkt niet te lukken. Bijv. GLANSDORF, F., "La caractère imprescriptible des exceptions" (noot onder Cass. 22 oktober 1987), RCJB 1991, (267) 270. In Iuris-M vind ik nergens een aparte mogelijkheid om ervoor te zorgen dat (noot onder Cass. 22 oktober 1987) niet tussen de aanhalingstekens staat. Bij de titel voegen gaat dus niet aangezien het dan binnen de aanhalingstekens geplaatst wordt. In welke ruimte kan dit gezet worden zodat het overeenstemmend hierboven is? Bedankt!

**Comment by DriekDe** [comment]
Er is inderdaad een verschil. Dit heeft te maken met de primaire bron waarnaar verwezen wordt. 
Als de inhoudelijke tekst uitdrukkelijk verwijst naar de rechtspraak wordt dit gebruikt in voetnoot: Cass. 22 oktober 1987, RCJB 1991, 267, noot F. GLANSDORF.
Als de inhoudelijke tekst uitdrukkelijk verwijst naar de noot die commentaar geeft op het arrest, is dit rechtsleer en geldt de verwijzing zoals hierboven. 
De weergave bij de rechtspraak is er (denk ik) om aan de lezer te laten weten: er is ook nog interessante rechtspraak die dieper op dit arrest ingaat.

**Comment by mvwestendorp** [comment]
> De weergave bij de rechtspraak is er (denk ik) om aan de lezer te laten weten: er is ook nog interessante rechtspraak die dieper op dit arrest ingaat.

Ik denk het ook. 

Het is even kijken naar een goed veld hiervoor. Verder is dat geen probleem om toe te voegen. Gezien het niet echt veel gebruikt wordt (denk ik) is het `extra` vak eventueel een mogelijkheid? Meningen daarover?

**Comment by ElisabethdL** [comment]
Wordt er gekozen voor ref. type 'artikel in academisch tijdschrift'?

**Comment by mvwestendorp** [comment]
> Wordt er gekozen voor ref. type 'artikel in academisch tijdschrift'?

Yes, artikel in tijdschrift. 
De titel geeft misschien wat verwarring, maar dat is hoe het in de V&A omschreven wordt.

**Comment by DriekDe** [comment]
Het extra vak lijkt me inderdaad geschikt daarvoor.
En het zou inderdaad gaan over type 'artikel in academisch tijdschrift'

**Comment by ElisabethdL** [comment]
Is het mogelijk om dat op beide manieren weer te geven? 
- tussen haakjes indien titel aanwezig tussen aanhalingstekens
- zonder haakjes of aanhalingstekens indien geen titel

Dan zou ik inderdaad kiezen voor 'extra'. Er zijn niet veel andere velden mogelijk of logisch. 'Short title' zou ik ook nog begrijpen.

**Comment by mvwestendorp** [comment]
Misschien is er wat verwarring.

> Als de inhoudelijke tekst uitdrukkelijk verwijst naar de noot die commentaar geeft op het arrest, is dit rechtsleer en geldt de verwijzing zoals hierboven.
De weergave bij de rechtspraak is er (denk ik) om aan de lezer te laten weten: er is ook nog interessante rechtspraak die dieper op dit arrest ingaat.

Dus de beide manieren zijn
1. De eerste manier is via het type: `tijdschrift` V&A rn 149
2. De tweede manier werkt al en gaat via het type `rechtszaak` V&A rn 107-

Die 2e manier blijft onveranderd. Voor de eerste ga ik kijken hoe dat aan `extra` is toe te voegen.

**Comment by ElisabethdL** [comment]
Ik bedoelde zoals V&A 149:

1. SWENNEN, F., "Vader moeder zult gij eren?" (noot onder Cass. 3 juni 2010), _RW_ 2010-11, 1648-1651
2. SENAEVE, P., noot onder Antwerpen 21 februari 1979, _RW_ 1978-79, 2328

In voorbeeld 1 heeft de noot een titel, in vb. 2 niet en moet de vermelding "noot onder" dus niet tussen haakjes, maar ook niet tussen aanhalingstekens.

In beide gevallen komt de auteur eerst, in tegenstelling tot V&A 107 e.v., waar het arrest eerst komt en de auteur van de noot laatst.

**Comment by mvwestendorp** [comment]
Na deze wijziging: a39a6dd52c5e4a0eca416ec3045a2bb10a51ce7b, geeft juris-m het volgende resultaat:

- P. SENAEVE, noot onder Antwerpen 21 februari 1979, _RW_ 1978-1979, 2328.
- F. SWENNEN, “Vader moeder zult gij eren?” (noot onder Cass. 3 juni 2010), _RW_ 2010-2011, 1648–1651.

Dat zijn dus correcte verwijzing (buiten #38) met gebruik van `noot: ARREST` in het `extra` veld. NB `noot:` is hierbij belangrijk.
![image](https://user-images.githubusercontent.com/902633/56491721-c3fff580-64e9-11e9-8f04-de92e9d9b462.png)
