### ISSUE TITLE
Rechtspraak in jaarboeken, caseboeken etc.

### ISSUE THREAD

**Issue by mvwestendorp** [mvwestendorp/v-en-a#29]
> 104. Het  komt  ook  voor  dat  rechtspraak  wordt  gepubliceerd  in  jaarboeken,  caseboeken,  cursussen  enz.  In  dat  geval  volgt  na rechterlijke instantie en datum (en eventuele verdere identificatie)  het  woord  ‘in’  en  de  gegevens  van  een  boek  zoals  verder besproken wordt, infra nr. 119 e.v.

Op dit moment geen ondersteuning voor V&A rn. 104.

**Comment by ElisabethdL** [comment]
Gemakkelijk op te lossen met een prefix?

**Comment by mvwestendorp** [comment]
veld `extra` = `case: ARREST`
Bijvoorbeeld: `case: Cass. 5 november 1920` bij een correct ingevuld boek van het voorbeeld in RN 104 geeft:
- Cass. 5 november 1920 in J. DUJARDIN en J. VANDE LANOTTE, _Inleiding tot het publiek recht, I, Basisbegrippen_, Brugge, Die Keure, 1997.
