### ISSUE TITLE
ECLI en nummer bij EU rechtspraak

### ISSUE THREAD

**Issue by mvwestendorp** [mvwestendorp/v-en-a#30]
Zie V&A rn. 94.
Alleen bij Hof van Justitie moet zowel een nummer als ECLI vermeld worden.

**Comment by DriekDe** [comment]
Lijkt me een goede oplossing :)

**Comment by mvwestendorp** [comment]
Ik heb toch geopteerd voor het toevoegen van de ecli aan het extra vak. 
Als later ECLI toegevoegd wordt als apart vak in Juris-M of aan de V&A dan staat het al goed/beter in een apart vak dan samengevoegd met een zaaknummer. Omdat het niet veel gebruikt wordt in de V&A op dit moment kan het in het `extra` vak.
Dus `Zaaknummer` = `C-120/78`
`extra` = `ecli: ECLI:EU:C:1979:42`
geeft het correct resultaat.
