### ISSUE TITLE
Automatische afkortingen voor tijdschriften en rechtbank

### ISSUE THREAD

**Issue by mvwestendorp** [mvwestendorp/v-en-a#34]
Afkortingen worden wel toegevoegd maar niet gebruikt. 
Uitzoeken of upstream probleem en dan daar melden.

**Comment by mvwestendorp** [comment]
Ook een probleem met de rechtbank.
`Section II, European Court of Human Rights` moet afkorten naar `EHRM (2e k.)`

**Comment by mvwestendorp** [comment]
Dus bij het 'correct' toevoegen van een verwijzing naar de rechtspraak van het EHRM (m.b.v. translator HUDOC) blijft op dit moment de Engelstalige waarde staan. 
Dus `European Court of Human Rights|Section II` i.p.v. `EHRM (2e k.)`.
Bijvoorbeeld: 
- Section II, European Court of Human Rights 16 april 2019, nr. 12778/17, Alparslan Altan/Turkey, http://hudoc.echr.coe.int/eng?i=001-192804.

NB omtrent URL #39

**Comment by mvwestendorp** [comment]
Tijdschriften werken wel op mijn installatie, rechtbanken nog niet.

**Comment by ElisabethdL** [comment]
Interessante resultaten met rechtbanken: 

> sc 14 december 2017, nr. C.16.0296.N, RABG 2018, 350, noot. B. MAES en L. VANNECKE.
> echr~section.2 16 april 2019, nr. 12778/17, Alparslan Altan/Turkey, http://hudoc.echr.coe.int/eng?i=001-192804. 
> ecj~chamber.8 20 november 2009, nr. C-278/09.

Maar "Tijdschrift voor privaatrecht" blijft gewoon staan...

**Comment by mvwestendorp** [comment]
Er is blijkbaar wat evolutie in de ondersteuning van rechtbanken. [Issue Juris-M](https://github.com/Juris-M/zotero/issues/62)
En in de mailinglist wordt er ook gesproken over veranderingen aan de abbreviation filter.

**Comment by ElisabethdL** [comment]
Tijdschriften werken ook nog altijd niet bij mij :(

**Comment by mvwestendorp** [comment]
De oplossing ligt dan bij Juris-M, ik heb contact opgenomen.
