### ISSUE TITLE
Valid court in juris-m library

### ISSUE THREAD

**Issue by mvwestendorp** [mvwestendorp/v-en-a#4]
Depends on valid court as currently being worked on https://fbennett.github.io/legal-resource-registry/

**Comment by mvwestendorp** [comment]
#34

**Comment by mvwestendorp** [comment]
Works now.

**Comment by ElisabethdL** [comment]
Bij mij nog steeds geen correcte rechtbanken. (Hier Bxl Rb. 1e aanleg)

>   cfi 27 januari 2011, Tijdschrift voor privaatrecht 2012, 651.

**Comment by mvwestendorp** [comment]
Versie van Juris-M?

**Comment by mvwestendorp** [comment]
Dan zou het erin moeten zitten. 
Ik ga overleggen. Zie #34.
