### ISSUE TITLE
Verkorte verwijzing niet bij eenmalige verwijzing

### ISSUE THREAD

**Issue by mvwestendorp** [mvwestendorp/v-en-a#43]
Verkorte verwijzing wordt ook toegevoegd wanneer er eenmalig verwezen wordt.

**Comment by ElisabethdL** [comment]
Enige wat niet klopt is:

> In een tekst zonder bibliografie wordt een eerste vermelding in voetnoot voluit geschreven, gevolgd door de verkorte vermelding na de woorden ‘hierna:’ tussen haakjes. 

Lijkt voldoende om dit in de bibliografie te vermelden. Kan ook met suffix? Alleen cursief toevoegen dan, voor titel van het werk.

**Comment by mvwestendorp** [comment]
Ik ben niet helemaal mee. Ik bedoelde dat als er bijvoorbeeld maar 1 verwijzing in de hele tekst staat, dat er dan nog (hierna: x) vermeld wordt. Dat is dus niet zo logisch. Wat bedoel jij precies?

In principe gaan verkorte verwijzingen niet via suffix maar automatisch. Als dat fout gaat met of zonder bibliografie dan moet ik daar naar kijken.

**Comment by ElisabethdL** [comment]
In de versie die ik heb (misschien niet de laatste) is dat niet het geval. Eerste (of enige) verwijzing geeft geen "hierna: <korte titel>". Wordt de korte titel bij "short title" ingevuld?

**Comment by mvwestendorp** [comment]
Krijg het niet meer gereproduceerd. Misschien toch verkeerd gezien.
