### ISSUE TITLE
Noot rechtspraak meerdere auteurs EN in hoofdletters

### ISSUE THREAD

**Issue by mvwestendorp** [mvwestendorp/v-en-a#47]
> Als er meerdere auteurs zijn bij een noot bij rechtspraak, dan komt de "en" ook in hoofdletters. Resultaat: Cass. 14 december 2017, nr. C.16.0296.N, RABG 2018, 350, noot B. MAES EN L. VANNECKE. Terwijl het dit moet zijn: Cass. 14 december 2017, nr. C.16.0296.N, RABG 2018, 350, noot B. MAES en L. VANNECKE

**Comment by mvwestendorp** [comment]
Werkt bij mij gewoon, kan het niet reproduceren.

**Comment by ElisabethdL** [comment]
Bij mij ook geen probleem.

**Comment by mvwestendorp** [comment]
Gebruik van een oude versie.
