### ISSUE TITLE
korte titel boek

### ISSUE THREAD

**Issue by ElisabethdL** [mvwestendorp/v-en-a#55]
Korte titel van een boek verschijnt niet in oorspronkelijke referentie of bibliografie. (zie V&A 174: je mag kiezen waar je de korte titel vermeldt, maar die moet ergens vermeld worden zodat de lezer weet waar het over gaat)

Eerste ref:
> H. DE PAGE en I. MASSON, _Traité élémentaire de droit civil belge_, II, _Les personnes_, Brussel, Bruylant, 1990.

Moet zijn:
> H. DE PAGE en I. MASSON, _Traité élémentaire de droit civil belge_, II, _Les personnes_, Brussel, Bruylant, 1990. (Hierna: H. DE PAGE en I. MASSON, _Traité_).

Tweede ref lijkt dan wel ok (behalve misschien de "e.a.")
> H. DE PAGE e.a., _Traité_, 2, _supra_ vn. 18.

**Comment by mvwestendorp** [comment]
Ik denk dat het nu werkt in de nieuwe master: https://github.com/mvwestendorp/v-en-a/blob/master/v-en-a.csl

**Comment by mvwestendorp** [comment]
Verkorte dingen zijn verwijderd zie a5d42f0277edc0ac0cbd27d79785f9ab367ac6b5
